"""Protected test (gate author: vdtpga). Pins `core.py` against `parity-fixture.json`, the exported
oracle the Swift port's `cutrules-parity` / `trigger-parity` self-test arms are measured against.

This is a two-way guardrail: `export_parity_fixture.py` writes the fixture FROM `core.py`, so by
construction it starts in sync; this test is what notices if a later edit to `core.py` ever drifts
away from the file the Swift port already trusts. Do not edit this file to make a drifted `core.py`
pass -- regenerate the fixture (if the behavior change is intended and core's own `test_core.py`
still passes) or fix `core.py` (if it is not).
"""

from __future__ import annotations

import json
import pathlib
import unittest

import core

FIXTURE_PATH = pathlib.Path(__file__).resolve().parent / "parity-fixture.json"


class ParityFixtureTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        cls.fixture = json.loads(FIXTURE_PATH.read_text(encoding="utf-8"))

    def test_fixture_file_has_the_expected_schema(self) -> None:
        self.assertEqual(self.fixture["schema"], "tailcheck-parity-fixture/1")
        self.assertTrue(self.fixture["trigger_cases"])
        self.assertTrue(self.fixture["accept_cut_cases"])

    def test_core_trigger_matches_every_fixture_case(self) -> None:
        for case in self.fixture["trigger_cases"]:
            with self.subTest(case=case["label"]):
                reasons = core.trigger(case["segments"], case["raw_text"], case["final_text"])
                self.assertEqual(sorted(reasons), case["expected_reasons_sorted"])

    def test_core_accept_cut_matches_every_fixture_case(self) -> None:
        for case in self.fixture["accept_cut_cases"]:
            with self.subTest(case=case["label"]):
                accepted, reason = core.accept_cut(
                    case["text"],
                    case["junk_suffix"],
                    boundaries=case["boundaries"],
                    max_words=case["max_words"],
                    max_share=case["max_share"],
                )
                self.assertEqual(accepted, case["expected_accepted"])
                self.assertEqual(reason, case["expected_reason"])


if __name__ == "__main__":
    unittest.main()
