#!/usr/bin/env python3
"""Protected grader (chain `vdtpga`, gate author GP). Pins the daemon-side half of the Phase 1
tailcheck contract (design note `Projects/viddydictate/notes/
trailing-gibberish-check-design-20261003.md`, 2026-10-06 "NEXT: Swift integration plan", Phase 1):

    the daemon's `_clean_segments` / `/transcribe` response carries the PRE-collapse per-segment
    raw text plus `no_speech_prob`/`avg_logprob`/`compression_ratio`/`start`/`end`, as an ADDITIVE
    field -- and every existing response field is unchanged.

This is a GATE, not an implementation: it is expected RED today, because `_clean_segments`
(`viddydictate_whisperd.py`) does not yet carry `no_speech_prob`/`avg_logprob`/`compression_ratio`
on its per-segment diagnostics records, and does not expose the pre-collapse text under a
`raw_text` key distinct from the (possibly short-run-collapsed) `text` key it already has. A later
link in this chain makes the daemon change; this file is what proves it did so additively, without
touching any existing field's name, type, or value. Do not edit this file to make today's daemon
pass -- change the daemon.

Runs with no mlx, no numpy, no network, no daemon process (mirrors
`scripts/test-whisperd-offline-warm.py`'s offline-only style): `_transcribe` itself is monkeypatched
out for the HTTP-response-shape checks, so nothing here ever imports mlx_whisper.
"""

from __future__ import annotations

import importlib.util
import io
import json
import pathlib
import sys
import types
from email.message import Message
from typing import Optional

sys.dont_write_bytecode = True
ROOT = pathlib.Path(__file__).resolve().parent.parent
DAEMON_PATH = ROOT / "viddydictate_whisperd.py"
TAG = "[tailcheck-diagnostics]"

FAILURES: list = []


def check(message: str, condition, detail: str = "") -> bool:
    if not isinstance(condition, bool):
        raise TypeError(f"check({message!r}, ...) needs a bool condition, got {type(condition).__name__}")
    print(f"{TAG} {'ok  ' if condition else 'FAIL'} {message}" + (f" ({detail})" if detail else ""))
    if not condition:
        FAILURES.append(message)
    return condition


def load_daemon() -> types.ModuleType:
    spec = importlib.util.spec_from_file_location("viddydictate_whisperd", DAEMON_PATH)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


# ---------------------------------------------------------------------------------------------
# (a) / (b): `_clean_segments` diagnostics directly -- no mlx, no numpy, no HTTP
# ---------------------------------------------------------------------------------------------

def gate_clean_segments_diagnostics(daemon: types.ModuleType) -> None:
    print(f"{TAG} --- (a)/(b) _clean_segments per-segment diagnostics ---")

    # Two segments: the second has a high compression ratio, so `_collapse_repeats` shortens the
    # TEXT used for the kept transcript -- the additive `raw_text` diagnostic must still carry the
    # PRE-collapse decode, distinct from the (possibly shortened) `text` the transcript assembly uses.
    repeated = "primarily primarily primarily primarily primarily primarily"
    segs = [
        {"start": 0.0, "end": 5.0, "text": "Checking in now.",
         "no_speech_prob": 0.05, "avg_logprob": -0.2, "compression_ratio": 1.0},
        {"start": 5.1, "end": 12.0, "text": repeated,
         "no_speech_prob": 0.4, "avg_logprob": -0.6, "compression_ratio": 3.0},
    ]
    result = {"text": "Checking in now. " + repeated, "segments": segs}
    _text, diagnostics = daemon._clean_segments(result, do_clean=True, audio_duration=12.0)

    check("(a) _clean_segments returns one diagnostic record per input segment",
          len(diagnostics) == len(segs), f"got {len(diagnostics)}")
    if len(diagnostics) != len(segs):
        return

    for i, (seg, record) in enumerate(zip(segs, diagnostics)):
        check(f"(a) record[{i}] keeps the existing 'start' field unchanged",
              record.get("start") == seg["start"])
        check(f"(a) record[{i}] keeps the existing 'end' field unchanged",
              record.get("end") == seg["end"])
        check(f"(a) record[{i}] has an ADDITIVE 'raw_text' equal to the PRE-collapse segment decode",
              record.get("raw_text") == seg["text"],
              f"want={seg['text']!r} got={record.get('raw_text')!r}")
        check(f"(a) record[{i}] has an ADDITIVE 'no_speech_prob' equal to the decode's own value",
              record.get("no_speech_prob") == seg["no_speech_prob"])
        check(f"(a) record[{i}] has an ADDITIVE 'avg_logprob' equal to the decode's own value",
              record.get("avg_logprob") == seg["avg_logprob"])
        check(f"(a) record[{i}] has an ADDITIVE 'compression_ratio' equal to the decode's own value",
              record.get("compression_ratio") == seg["compression_ratio"])

    # (b) the pre-existing fields (kept/drop_reason/text/effective_end) are untouched in shape:
    # pin them against today's known-good behavior so a later "additive" change cannot quietly
    # start altering what they mean.
    check("(b) record[0] (kept) still reports kept=True, drop_reason=None",
          diagnostics[0].get("kept") is True and diagnostics[0].get("drop_reason") is None)
    check("(b) record[0] still carries the pre-existing 'text' field, unchanged",
          diagnostics[0].get("text") == segs[0]["text"])
    check("(b) record[0] still carries the pre-existing 'effective_end' field, unchanged",
          diagnostics[0].get("effective_end") == segs[0]["end"])


# ---------------------------------------------------------------------------------------------
# (c): the full /transcribe HTTP response, through Handler.do_POST -- `_transcribe` monkeypatched
# out, so nothing here ever imports mlx_whisper or numpy.
# ---------------------------------------------------------------------------------------------

def make_post_handler(daemon: types.ModuleType, body: bytes) -> "object":
    handler = daemon.Handler.__new__(daemon.Handler)
    handler.path = "/transcribe"
    handler.command = "POST"
    handler.request_version = "HTTP/1.1"
    handler.requestline = "POST /transcribe HTTP/1.1"
    handler.client_address = ("127.0.0.1", 0)
    handler.close_connection = False
    headers = Message()
    headers["Content-Length"] = str(len(body))
    handler.headers = headers
    handler.rfile = io.BytesIO(body)
    handler.wfile = io.BytesIO()
    return handler


def run_post(daemon: types.ModuleType, body: bytes) -> dict:
    handler = make_post_handler(daemon, body)
    handler.do_POST()
    raw = handler.wfile.getvalue()
    head, _, response_body = raw.partition(b"\r\n\r\n")
    assert head.startswith(b"HTTP/1.1 200"), head.split(b"\r\n")[0]
    return json.loads(response_body)


def gate_transcribe_response_additive(daemon: types.ModuleType) -> None:
    print(f"{TAG} --- (c) /transcribe response: additive segments field, everything else unchanged ---")

    daemon._ready.set()
    daemon._load_error[0] = None

    seg = {"start": 0.0, "end": 5.0, "text": "Checking in now.",
           "no_speech_prob": 0.05, "avg_logprob": -0.2, "compression_ratio": 1.0}

    def fake_transcribe(_path, cond_prev=None, clean=None, initial_prompt=None):
        raw = "Checking in now."
        text, diagnostics = daemon._clean_segments(
            {"text": raw, "segments": [dict(seg)]}, True, audio_duration=5.0)
        return raw, text, diagnostics, 5.0

    daemon._transcribe = fake_transcribe

    response = run_post(daemon, b"fake-audio-bytes")

    check("(c) 'transcript' is unchanged in meaning (the post-cleanup text)",
          response.get("transcript") == "Checking in now.")
    check("(c) 'raw_transcript' is unchanged in meaning (the pre-cleanup text)",
          response.get("raw_transcript") == "Checking in now.")
    check("(c) 'model' is still present", isinstance(response.get("model"), str))
    check("(c) 'parameters' is still present with its documented keys",
          isinstance(response.get("parameters"), dict)
          and "audio_duration_s" in response["parameters"]
          and "initial_prompt_chars" in response["parameters"])

    segments_out = response.get("segments")
    check("(c) 'segments' is still present and has one entry",
          isinstance(segments_out, list) and len(segments_out) == 1,
          str(segments_out))
    if not (isinstance(segments_out, list) and len(segments_out) == 1):
        return
    record = segments_out[0]
    check("(c) the wire-level segment record carries the ADDITIVE 'raw_text'",
          record.get("raw_text") == seg["text"], json.dumps(record))
    check("(c) the wire-level segment record carries the ADDITIVE 'no_speech_prob'",
          record.get("no_speech_prob") == seg["no_speech_prob"])
    check("(c) the wire-level segment record carries the ADDITIVE 'avg_logprob'",
          record.get("avg_logprob") == seg["avg_logprob"])
    check("(c) the wire-level segment record carries the ADDITIVE 'compression_ratio'",
          record.get("compression_ratio") == seg["compression_ratio"])
    check("(c) the wire-level segment record still carries 'start'/'end' unchanged",
          record.get("start") == seg["start"] and record.get("end") == seg["end"])


def main() -> int:
    daemon = load_daemon()
    gate_clean_segments_diagnostics(daemon)
    daemon = load_daemon()  # fresh module: (c) monkeypatches module globals
    gate_transcribe_response_additive(daemon)
    if FAILURES:
        print(f"{TAG}[FAIL] {len(FAILURES)} check(s) failed: " + "; ".join(FAILURES))
        return 1
    print(f"{TAG}[PASS] daemon diagnostics carry the additive pre-collapse per-segment fields, "
          "existing fields unchanged")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
