import Foundation
import AppKit

extension NotesProbe {
    static func probeStoreRoundTrip(freshRoot: () -> URL, check: Check) {
        // --- 1. create / save / load round-trip -------------------------------------------------
        do {
            let store = StickyNotesStore(root: freshRoot())
            store.saveOpenNote(id: "note-alpha", body: "# Hello\nworld")
            let notes = store.openNotes()
            check("round-trip: saved note loads back with id + body intact",
                  notes.count == 1 && notes.first?.id == "note-alpha" && notes.first?.body == "# Hello\nworld")
        }
    }

    static func probeTitleDerivation(fm: FileManager, freshRoot: () -> URL, check: Check) {
        // --- 2. title derivation + 20-char cap + rename override --------------------------------
        do {
            check("title: first non-empty line, markdown-stripped",
                  StickyNotesStore.title(for: "\n## Groceries list\n- milk") == "Groceries list")
            check("title: Untitled fallback for blank body",
                  StickyNotesStore.title(for: " \n\t ") == "Untitled")
            // truncatedTitle caps at 20: 17-char prefix + "..." for anything longer.
            check("title: 20-char cap (prefix 17 + ellipsis)",
                  StickyNotesStore.title(for: "abcdefghijklmnopqrstuvwxyz") == "abcdefghijklmnopq...")

            let store = StickyNotesStore(root: freshRoot())
            store.saveOpenNote(id: "note-alpha", body: "# Hello\nworld")
            store.renameNote(id: "note-alpha", title: "My Custom")
            check("rename override wins over body-derived title",
                  store.openNotes().first?.title == "My Custom")
            let titlesURL = store.root.appendingPathComponent("note-titles.json")
            let titlesJSON = (try? String(contentsOf: titlesURL, encoding: .utf8)) ?? ""
            check("rename override persists to note-titles.json",
                  fm.fileExists(atPath: titlesURL.path)
                  && titlesJSON.contains("note-alpha") && titlesJSON.contains("My Custom"))
            store.renameNote(id: "note-alpha", title: "")
            check("blank rename clears override, reverts to body title",
                  store.openNotes().first?.title == "Hello"
                  && !fm.fileExists(atPath: titlesURL.path))
        }
    }

    static func probeAggregateRegeneration(freshRoot: () -> URL, check: Check) {
        // --- 3. _open-notes.md regeneration: tab order + active marker -------------------------
        do {
            let store = StickyNotesStore(root: freshRoot())
            store.saveOpenNote(id: "note-a", body: "# Groceries\n- milk")
            store.saveOpenNote(id: "note-b", body: "Second note body")
            store.rewriteAggregate(tabOrder: ["note-b", "note-a"], activeId: "note-a")
            let agg = (try? String(contentsOf: store.root.appendingPathComponent("_open-notes.md"), encoding: .utf8)) ?? ""
            check("aggregate: honors passed tab order (note-b section precedes note-a)",
                  orderedBefore("## Second note body", "## Groceries", in: agg))
            check("aggregate: marks exactly the active tab",
                  agg.contains("## Groceries (active)")
                  && countOccurrences(of: " (active)", in: agg) == 1)
            check("aggregate: read-only auto-generated header, no frontmatter",
                  agg.hasPrefix("<!-- Auto-generated by ViddyDictate. Read-only."))
        }
    }

    static func probeCloseHistoryLifecycle(freshRoot: () -> URL, check: Check) -> Bool {
        // --- 4. close -> history -> restore -> hard-delete ------------------------------------
        do {
            let store = StickyNotesStore(root: freshRoot())
            store.saveOpenNote(id: "note-close", body: "# Closeme\ncontent")
            store.closeNote(id: "note-close", body: "# Closeme\ncontent")
            check("close: removed from open notes, present in history",
                  store.openNotes().isEmpty
                  && store.history(retention: .forever).contains { $0.title == "Closeme" })

            guard let histId = store.history(retention: .forever).first(where: { $0.title == "Closeme" })?.id else {
                check("close: history row has an id", false); return false }
            let restored = store.restoreHistory(id: histId)
            check("restore: reopens the note with its body, drops it from history",
                  restored?.body == "# Closeme\ncontent"
                  && store.openNotes().count == 1
                  && !store.history(retention: .forever).contains { $0.id == histId })

            // Re-close, then hard-delete from history.
            store.closeNote(id: restored?.id ?? "note-close", body: restored?.body ?? "")
            guard let delId = store.history(retention: .forever).first?.id else {
                check("hard-delete: a history row exists to delete", false); return false }
            store.deleteHistory(id: delId)
            check("hard-delete: deleteHistory removes the row for good",
                  !store.history(retention: .forever).contains { $0.id == delId })
        }

        return true
    }

    static func probeRetentionPurge(fm: FileManager, freshRoot: () -> URL, check: Check) {
        // --- 5. retention purge: 24h / 1 week / forever --------------------------------------
        // Seed three history rows with fixed closed-at ages directly on disk (the store has no clock
        // seam), then cascade retentions from loosest to strictest. Each history() call purges in place,
        // so forever(3) -> oneWeek(2, drops the 10-day) -> oneDay(1, drops the 2-day) is monotonic.
        do {
            let store = StickyNotesStore(root: freshRoot())   // init purge runs here on an empty store
            let now = Date()
            let seeded: [(id: String, ageHours: Double)] = [
                ("note-fresh", 12), ("note-2day", 48), ("note-10day", 240),
            ]
            seedHistory(root: store.root,
                        entries: seeded.map { ($0.id, "\($0.id).md", now.addingTimeInterval(-$0.ageHours * 3600)) })
            check("retention forever: keeps all rows regardless of age",
                  store.history(retention: .forever).count == 3)
            let week = store.history(retention: .oneWeek)
            check("retention 1 week: purges rows older than 7 days only",
                  week.count == 2 && !week.contains { $0.id == "note-10day" })
            let day = store.history(retention: .oneDay)
            check("retention 24 hours: purges rows older than a day",
                  day.count == 1 && day.first?.id == "note-fresh")
            check("retention purge is destructive on disk (10-day file gone)",
                  !fm.fileExists(atPath: store.root.appendingPathComponent("notes-history/note-10day.md").path))
        }
    }

    static func probeSaveAs(fm: FileManager, base: URL, freshRoot: () -> URL, check: Check) {
        // --- 6. save-as naming + never-overwrite dedup --------------------------------------
        do {
            let store = StickyNotesStore(root: freshRoot())
            let body = "# My Report\ncontent here"
            store.saveOpenNote(id: "note-sa", body: body)
            let dest = base.appendingPathComponent("exports", isDirectory: true)
            do {
                let u1 = try store.saveAs(id: "note-sa", body: body, destination: dest)
                check("save-as: writes a .md file whose name derives from the title",
                      u1.pathExtension == "md" && u1.lastPathComponent.hasPrefix("my-report-")
                      && fm.fileExists(atPath: u1.path))
                // A second save of the same note must never overwrite: saveAs loops until the path is
                // free, so it is guaranteed to return a distinct, still-present file (deterministic —
                // independent of whether the dedup suffix or a new timestamp makes it distinct).
                let u2 = try store.saveAs(id: "note-sa", body: body, destination: dest)
                check("save-as: second save never overwrites, yields a distinct existing file",
                      u2 != u1 && fm.fileExists(atPath: u1.path) && fm.fileExists(atPath: u2.path)
                      && u2.lastPathComponent.hasPrefix("my-report-"))
            } catch {
                check("save-as: did not throw", false, "\(error)")
            }
        }
    }

    static func probeEmptyNoteEvaporation(fm: FileManager, freshRoot: () -> URL, check: Check) {
        // --- 7. empty-note evaporation -----------------------------------------------------
        do {
            let store = StickyNotesStore(root: freshRoot())
            let noteURL = store.root.appendingPathComponent("note-empty.md")
            store.saveOpenNote(id: "note-empty", body: "   \n\t ")
            check("evaporation: whitespace-only body never materializes a file",
                  store.openNotes().isEmpty && !fm.fileExists(atPath: noteURL.path))
            store.saveOpenNote(id: "note-empty", body: "real content")
            check("evaporation: materializes once given real content",
                  store.openNotes().count == 1 && fm.fileExists(atPath: noteURL.path))
            store.saveOpenNote(id: "note-empty", body: "   ")
            check("evaporation: emptying an existing note deletes its file",
                  store.openNotes().isEmpty && !fm.fileExists(atPath: noteURL.path))
        }
    }

    static func probeDuplicateNote(freshRoot: () -> URL, check: Check) {
        // --- 8. duplicate note store outcome (L2) -------------------------------------------
        // The web-island "Duplicate note" action mints a fresh id, saves the same body, and applies a
        // "<source title> copy" rename override (reusing MSG.inbound.save + MSG.inbound.rename), inserting
        // the copy right of the source. Assert that store outcome directly: a distinct note with identical body and the
        // copy title override, the source untouched, and the copy ordered immediately after it.
        do {
            let store = StickyNotesStore(root: freshRoot())
            store.saveOpenNote(id: "note-src", body: "# Plans\nbody text")
            let srcTitle = store.openNotes().first { $0.id == "note-src" }?.title ?? ""
            let dupId = StickyNotesStore.newNoteId()
            store.saveOpenNote(id: dupId, body: "# Plans\nbody text")
            store.renameNote(id: dupId, title: "\(srcTitle) copy")
            let notes = store.openNotes()
            let src = notes.first { $0.id == "note-src" }
            let dup = notes.first { $0.id == dupId }
            check("duplicate: mints a distinct note id, source retained",
                  notes.count == 2 && dupId != "note-src" && src != nil && dup != nil)
            check("duplicate: copy carries the same body",
                  dup?.body == "# Plans\nbody text")
            check("duplicate: copy title override is '<source title> copy'",
                  srcTitle == "Plans" && dup?.title == "Plans copy")
            check("duplicate: source note body + title unchanged",
                  src?.body == "# Plans\nbody text" && src?.title == "Plans")
            store.rewriteAggregate(tabOrder: ["note-src", dupId], activeId: dupId)
            let agg = (try? String(contentsOf: store.root.appendingPathComponent("_open-notes.md"), encoding: .utf8)) ?? ""
            check("duplicate: copy sits immediately right of source in aggregate order",
                  orderedBefore("## Plans\n", "## Plans copy", in: agg))
        }
    }

}
